[build]
  command = "CI=false npm run build"
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 